version: "3.0"
#NETWORK
networks:
  net-web:
    driver: bridge

#VOLUMES
services:
  #container php
  my-php:
    # name CTN
    container_name: web-php
    build:
      dockerfile: Dockerfile
      context: .
    hostname: php
    restart: always
    networks:
      - net-web
    volumes:
      - ./:/home/web
  #container NGINX
  my-nginx:
    container_name: proxy-nginx
    image: "nginx:latest"
    hostname: nginx
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    networks:
      - net-web
    volumes:
      - ./:/home/web
      - ./server/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./server/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
  #container MySql
  my-sql:
    container_name: db-mysql
    image: "mysql:latest"
    hostname: mysql
    restart: always
    networks:
      - net-web
    command: >
      bash -c "
      chmod 644 /etc/mysql/my.cnf
      && /entrypoint.sh mysqld"
    volumes:
      - ./server/mysql/db:/var/lib/mysql
      - ./server/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=121212
      - MYSQL_DATABASE=e_commerce
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=e_commerce1212

  my-mongo:
    container_name: db-mongo
    image: mongo:5.0.2
    restart: always
    networks:
      - net-web
    volumes:
      - ./server/mongo/db:/data/db
